# Generated by Django 5.2.5 on 2025-09-02 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='owner',
        ),
    ]
